### ISSUE TITLE
Extension doesn't show up in Extensions

### ISSUE THREAD

**Issue by saikyun** [janet-lang/vscode-janet#10]
After having cloned the repo into `~/.vscode/extensions` it doesn't show up in my Extensions tab, so I can't enable it.

Looked around in vscode docs but couldn't find a way to enable it outside generating some sort of installation file.

**Comment by sogaiu** [comment]
I think it's possible vscode may be different now.

I also experienced similar results trying the instructions in the README.

Here's what worked for me:

* Ensure Node.js >= 14 is available (I tried nvm, but [volta](https://volta.sh/) -- available via brew too -- should also work IIUC) -- [a 12.x series Node.js didn't work for me](https://github.com/microsoft/vscode-vsce/issues/653#issuecomment-1152130848)
* git clone https://github.com/janet-lang/vscode-janet
* cd vscode-janet
* npm install
* npm install vsce
* vsce package
* start vscode (or vscodium)
* File -> Preferences -> Extensions
* In the EXTENSIONS tab(?), click on the `...` at the right (see the image below)
* Choose "Install from VSIX..."
* Find and select the `.vsix` file - here it was `vscode-janet-0.0.2.vsix` and it was in the `vscode-janet` folder where the `vsce package` invocation was done

Surely it would be nicer to have fewer steps or have it be more automated [1].  May be there is a way.  I think there used to be [2].

![install-from-vsix](https://user-images.githubusercontent.com/33044872/214715282-3096b882-68d1-4932-b451-6dc73e42482e.png)

---

[1] Looks like one can do the following sort of thing via the command line:
```
codium --install-extension vscode-janet-0.0.2.vsix
```
For vscode, the command line executable name might be `code`.  Not sure.

[2] Some [discussion](https://github.com/microsoft/vscode/issues/25159) here...

**Comment by sogaiu** [comment]
There is sort of an alternative method that goes like this:

* Open vscode (or vscodium)
* Open the vsode-janet folder in the program
* Choose Run -> Run without Debugging

I think that should open a new window with the extension running.

Perhaps this is meant for development of the extension itself.

**Comment by saikyun** [comment]
Thanks, the steps worked other than having to do `npm install -g vsce`. Couldn't remember how to run it from the local install. :)

**Comment by sogaiu** [comment]
@saikyun Good to hear things are working for you.

---

On a side note, may be you are aware of this already, but FWIW, for npm / node stuff, I believe one can get into trouble using `-g`.  In the npm / node world where backward compatibility doesn't seem to be such a priority and there is a lot of change, using project-specific things via `npx` seems like less trouble to me.

**Comment by saikyun** [comment]
Yeah, I agree it's not optimal to use -g. Do you know how to run vsce
locally instead? :O Tried npm run but that was not right, that was only for
scripts in the npm-file :V Too long since I used npm.

Den fre 27 jan. 2023 kl 01:03 skrev sogaiu ***@***.***>:

**Comment by sogaiu** [comment]
I think what I did was:
```
cd vscode-janet
npm install vsce
npx vsce package
```
`npx` is our friend :)
