### ISSUE TITLE
Publish to open-vsx.org

### ISSUE THREAD

**Issue by dokutan** [janet-lang/vscode-janet#15]
It would be awesome if you could also publish this extension to [open-vsx.org](https://open-vsx.org/). This would make it much easier to install on forks of VSCode like VSCodium, which are not allowed to use the official marketplace.

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by CFiggers** [comment]
I can do that. 🙂 I'm the current publisher of the listing on the VS Code marketplace and I've listed things on open-vsix.org before.

**Comment by CFiggers** [comment]
The extension is now published on open-vsx.org:

https://open-vsx.org/extension/janet-lang/vscode-janet 

If/when there's ever a need to version bump the extension, I'll make sure to update both places.

**Comment by dokutan** [comment]
Thank you very much
